#!/bin/bash

exiftool -filename -filemodifydate -createdate -r -if '(not $datetimeoriginal) and $filetype eq "JPEG"' .


exiftool -filename -filemodifydate -createdate -r -if '(not $datetimeoriginal or ($datetimeoriginal eq "0000:00:00 00:00:00"))' .

exiftool -filename -filemodifydate -createdate -r -if '(not $createdate  or ($createdate eq "0000:00:00 00:00:00"))' .


exiftool -m -d "%Y/%m/%Y-%m-%d %H.%M.%S%%-c.%%le" "-filename<FileInodeChangeDate" "-filename<ModifyDate" "-filename<CreateDate" "-filename<CreationDate" "-filename<DateTimeOriginal" .
exiftool -m -d "%Y/%m/%Y-%m-%d %H.%M.%S%%-c.%%le" "-testname<FileInodeChangeDate" "-testname<ModifyDate" "-testname<CreateDate" "-testname<CreationDate" "-testname<DateTimeOriginal" .
