#!/bin/bash

usage() { echo "Usage: $0 sourcedir 1>&2; exit 1; }

# show help
if [ "$#" -lt 1 ] ; then
	usage
fi

exiftool -r -m -d "RAW/%Y/%m/%Y-%m-%d %H.%M.%S%%-c.%%le" \
  -if '$filename !~ /^\./' \
  "-filename<FileInodeChangeDate" "-filename<ModifyDate" "-filename<CreateDate" "-filename<CreationDate" "-filename<DateTimeOriginal" \
  -ext cr2 "$@"
