#!/bin/bash

echo 'TODO options... organize [--images|--raw|--videos|--all] directory'
exit

# videos
exiftool -r -m -d "Video/%Y/%Y-%m-%d %H.%M.%S%%-c.%%le" \
  "-filename<FileInodeChangeDate" "-filename<ModifyDate" "-filename<CreateDate" "-filename<CreationDate" "-filename<DateTimeOriginal" \
  -if '$filename !~ /^\./' \
  -ext mp4 -ext avi -ext mov "$@"

# images

exiftool -r -m -d "Pictures/%Y/%m/%Y-%m-%d %H.%M.%S%%-c.%%le" \
  "-filename<FileInodeChangeDate" "-filename<ModifyDate" "-filename<CreateDate" "-filename<CreationDate" "-filename<DateTimeOriginal" \
  -if '$filename !~ /^\./' \
  -ext jpg "$@"

# raws

exiftool -r -m -d "RAW/%Y/%m/%Y-%m-%d %H.%M.%S%%-c.%%le" \
  -if '$filename !~ /^\./' \
  "-filename<FileInodeChangeDate" "-filename<ModifyDate" "-filename<CreateDate" "-filename<CreationDate" "-filename<DateTimeOriginal" \
  -ext cr2 "$@"
